cluster:
  bootstrap:
    name: k3s
    version: v1.21.5+k3s2
  kubectl:
    version: v1.21.5
  k9s:
    version: v0.24.15
  prefix: my90
  vm:
    box: generic/ubuntu1804
    version: 3.4.2
    cpus: 4
    memory: 2048
  token: helloworld
  server:
    name: master
    ip: 10.20.90.90
  workers:
    - name: worker1
      ip: 10.20.90.91
    - name: worker2
      ip: 10.20.90.92
    - name: worker3
      ip: 10.20.90.93
