cluster:
  bootstrap:
    name: k3s
    version: v1.22.2+k3s2
  kubectl:
    version: v1.22.2
  k9s:
    version: v0.24.15
  stern:
    version: 1.11.0
  kubelet:
    log-level: 8
  prefix: ku60
  vm:
    box: generic/ubuntu1804
    version: 3.5.2
    cpus: 2
    memory: 2048
  token: helloworld
  server:
    name: master
    ip: 10.20.90.60
  workers:
    - name: worker1
      ip: 10.20.90.61
    - name: worker2
      ip: 10.20.90.62
    - name: worker3
      ip: 10.20.90.63
    - name: worker4
      ip: 10.20.90.64
