cluster:
  bootstrap:
    name: k3s
    version: v1.21.6+k3s1
  kubectl:
    version: v1.21.6
  k9s:
    version: v0.24.15
  stern:
    version: 1.11.0
  kubelet:
    log-level: 5
  prefix: rancher50
  vm:
    box: generic/ubuntu1804
    version: 3.5.2
    cpus: 2
    memory: 4096
    disk-size: 50
    additional-disk-size: 5
    additional-disk-filesystem: xfs
  token: helloworld
  server:
    name: master
    ip: 10.20.90.50
  workers:
    - name: worker1
      ip: 10.20.90.51
