cluster:
  bootstrap:
    name: k3s
    version: v1.21.5+k3s2
  kubectl:
    version: v1.21.5
  k9s:
    version: v0.24.15
  kubelet:
    log-level: 2
  prefix: my50
  vm:
    box: generic/ubuntu1804
    version: 3.4.2
    cpus: 4
    memory: 2048
  token: helloworld
  server:
    name: master
    ip: 10.20.90.50
  workers:
    - name: worker1
      ip: 10.20.90.51
