cluster:
  bootstrap:
    name: k3s
    version: v1.23.6+k3s1
  kubectl:
    version: v1.23.6
  k9s:
    version: v0.24.15
  stern:
    version: 1.11.0
  kubelet:
    log-level: 2
  prefix: rancher50
  vm:
    box: generic/ubuntu2004
    version: "3.6.14"
    cpus: 2
    memory: 8192
    disk-size: 50
    additional-disk-size: 0
    additional-disk-filesystem: ext4
  token: helloworld
  server:
    name: master
    ip: 10.20.90.50
  workers:
    - name: worker1
      ip: 10.20.90.51
    - name: worker2
      ip: 10.20.90.52
    - name: worker3
      ip: 10.20.90.53
