#!/bin/bash

PROGNAME=$(basename $0)

CONFFILE=`realpath ./config.yaml`
FORCE=0

usage()
{
cat << EOF
$PROGNAME -- create a kubernetes cluster using KVM/QEMU and RKE2|K3s in minutes
Usage:
$PROGNAME start [--config <path>]           bootstrap a Kubernetes cluster
$PROGNAME stop [--config <path>]            destroy the Kubernetes cluster

$PROGNAME power-up name [--config <path>]   power up the specified node
$PROGNAME power-down name [--config <path>] power down the specified node
$PROGNAME help                              display help
EOF
}

function do_start () {
	echo "Start using $CONFFILE"

	pushd ./vagrant
        KUBE_VIRTDEPLOY_CONFIG="$CONFFILE" VAGRANT_VAGRANTFILE=Vagrantfile.server vagrant up
	KUBE_VIRTDEPLOY_CONFIG="$CONFFILE" VAGRANT_VAGRANTFILE=Vagrantfile.worker vagrant up
	popd
}

function do_stop () {
	echo "Stop using $CONFFILE"

	pushd ./vagrant
	env KUBE_VIRTDEPLOY_CONFIG="$CONFFILE" VAGRANT_VAGRANTFILE=Vagrantfile.server vagrant destroy
	env KUBE_VIRTDEPLOY_CONFIG="$CONFFILE" VAGRANT_VAGRANTFILE=Vagrantfile.worker vagrant destroy
	popd
}

function do_power_up () {
	NODE="$1"

	echo "Power up \`$NODE\`"

	if [[ "$NODE" =~ "master" ]]; then
		echo "master"
		VAGRANTFILE=Vagrantfile.server
	else
		VAGRANTFILE=Vagrantfile.worker
	fi

	pushd ./vagrant
	env KUBE_VIRTDEPLOY_CONFIG="$CONFFILE" VAGRANT_VAGRANTFILE="$VAGRANTFILE" vagrant up "$NODE"
	popd
}

function do_power_down () {
	NODE="$1"

	echo "Power up \`$NODE\`"

	if [[ "$NODE" =~ "master" ]]; then
		echo "master"
		VAGRANTFILE=Vagrantfile.server
	else
		VAGRANTFILE=Vagrantfile.worker
	fi

	pushd ./vagrant
        if [ "x$FORCE" == x"0" ]; then
                env KUBE_VIRTDEPLOY_CONFIG="$CONFFILE" VAGRANT_VAGRANTFILE="$VAGRANTFILE" vagrant halt "$NODE"
        else
                env KUBE_VIRTDEPLOY_CONFIG="$CONFFILE" VAGRANT_VAGRANTFILE="$VAGRANTFILE" vagrant halt --force "$NODE"
        fi

	popd
}

##################################################
# Main logic.
##################################################
# parse arguments and options.
declare -a params=()

for OPT in "$@"
do
	case "$OPT" in
		'--config' )
			if [[ -z "${2:-}" ]] || [[ "${2:-}" =~ ^-+ ]]; then
				echo "${PROGNAME}: option '$1' requires an argument." 1>&2
				exit 1
			fi
			CONFFILE=`realpath "$2"`
			shift 2
		;;
		'--force' )
			FORCE=1
			shift 1
		;;
		-*)
			echo "${PROGNAME}: illegal option -- '$(echo $1 | sed 's/^-*//')'" 1>&2
			exit 1
			;;
		*)
			if [[ ! -z "${1:-}" ]] && [[ ! "${1:-}" =~ ^-+ ]]; then
				params+=( "$1" )
				shift 1
			fi
			;;
	esac
done

command="" && [ ${#params[@]} -ne 0 ] && command="${params[0]}"

case $command in
	'start' )
		if [ ${#params[@]} -eq 1 ]; then
			do_start
		else
			exit 1
		fi
		;;
	'stop' )
		if [ ${#params[@]} -eq 1 ]; then
			do_stop
		else
			exit 1
		fi
		;;
	'power-up' )
		if [ ${#params[@]} -eq 2 ]; then
			do_power_up "${params[1]}"
		else
			exit 1
		fi
		;;
	'power-down' )
		if [ ${#params[@]} -eq 2 ]; then
			do_power_down "${params[1]}"
		else
			exit 1
		fi
		;;
	'help' )
		usage
		exit 0
		;;
	'' )
		echo "Try \`${PROGNAME} help' for more information."
		exit 0
		;;
	*)
		echo "${PROGNAME}: illegal command '$command'" 1>&2
		exit 1
		;;
esac
