#!/bin/bash

echo ">>> Installing customized"

git clone https://github.com/longhorn/longhorn.git

truncate -s 50G /home/vagrant/blockfile && sudo losetup --direct-io=on /dev/loop0 /home/vagrant/blockfile

exit 0







git clone -b v1.4.2 https://github.com/longhorn/longhorn.git longhorn-v1.4.2 
git clone https://github.com/longhorn/longhorn.git longhorn-v1.5.x


cat <<EOF > rwx.yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: test-statefulset-rwx
  namespace: default
spec:
  selector:
    matchLabels:
      app: test-statefulset-rwx
  serviceName: test-statefulset-rwx
  replicas: 1
  template:
    metadata:
      labels:
        app: test-statefulset-rwx
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - image: busybox
          imagePullPolicy: IfNotPresent
          name: sleep
          args: ['/bin/sh', '-c', 'while true;do date;sleep 5; done']
          volumeMounts:
            - name: pod-data
              mountPath: /data
  volumeClaimTemplates:
    - metadata:
        name: pod-data
      spec:
        accessModes: ['ReadWriteMany']
        storageClassName: 'longhorn-test'
        resources:
          requests:
            storage: 1Gi
EOF


cat <<EOF > sc.yaml
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: longhorn-test
provisioner: driver.longhorn.io
allowVolumeExpansion: true
reclaimPolicy: Delete
volumeBindingMode: Immediate
parameters:
  numberOfReplicas: "1"
  staleReplicaTimeout: "2880"
  fromBackup: ""
  fsType: "ext4"
EOF

exit 0

