#!/bin/bash

echo ">>> Installing customized"

echo "vm.nr_hugepages=1024" >> /etc/sysctl.conf

truncate -s 20G /home/vagrant/blockfile1
losetup --direct-io=on /dev/loop11 /home/vagrant/blockfile1

truncate -s 20G /home/vagrant/blockfile2
losetup --direct-io=on /dev/loop12 /home/vagrant/blockfile2

exit 0
