# -*- mode: ruby -*-
# # # vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

config_file = YAML.load_file('../config.yaml')
cluster = config_file['cluster']

bootstrap = config_file['cluster']['bootstrap']
kubectl = config_file['cluster']['kubectl']
kubelet = config_file['cluster']['kubelet']

vm = config_file['cluster']['vm']
server = config_file['cluster']['server']
workers = config_file['cluster']['workers']

$write_rke2_config=<<SCRIPT
cat <<EOF > /etc/rancher/rke2/config.yaml
server: https://${1}:9345
token: ${2}
node-external-ip: ${3}
node-ip: ${3}
kubelet-arg: "--v=4"
EOF
SCRIPT

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.provider :libvirt do |libvirt|
    libvirt.driver = "kvm"
  end

  config.vm.box = vm['box']
  config.vm.box_version = vm['version']

  config.vm.provision "net",
    type: "shell",
    path: "../scripts/fix.generic-ubuntu-dns.sh",
    privileged: true,
    run: "always"

  config.vm.provision "shell",
    run: "always",
    inline: "route add default gw 10.20.90.1"

  config.vm.provision "shell", privileged: true, inline: <<-SHELL
    set -e -x -u
    export DEBIAN_FRONTEND=noninteractive

    apt-get update -y
    apt-get install -y git vim curl build-essential openssh-server
    apt-get install -y jq open-iscsi nfs-common
  SHELL

  if bootstrap['name'] == 'rke2'
    config.vm.provision "shell", privileged: true, inline: <<-SHELL
      set -e -x -u
      export DEBIAN_FRONTEND=noninteractive

      echo "export CRI_CONFIG_FILE=/var/lib/rancher/rke2/agent/etc/crictl.yaml" >> /root/.bashrc
      echo "export PATH=$PATH:/var/lib/rancher/rke2/bin" >> /root/.bashrc
    SHELL
  elsif bootstrap['name'] == 'k3s'
    config.vm.provision "shell", privileged: true, inline: <<-SHELL
      set -e -x -u
      export DEBIAN_FRONTEND=noninteractive
    SHELL
  end

  # Worker nodes
  workers.each do |worker|
    hostname = "#{cluster['prefix']}-#{worker['name']}"
    ip = "#{worker['ip']}"

    config.vm.define "#{hostname}" do |node|
      node.vm.hostname = "#{hostname}"
      node.vm.network "public_network",
        :dev => "br0",
        :mode => "bridge",
        :type => "bridge",
        :ip => "#{ip}",
        :netmask => "255.255.254.0"
      node.vm.provider "libvirt" do |v|
        v.cpus = vm['cpus']
        v.memory = vm['memory']
      end
      # Start worker service
      if bootstrap['name'] == 'rke2'
        node.vm.provision "shell", privileged: true, inline: "curl -sfL https://get.rke2.io | INSTALL_RKE2_TYPE=\"agent\" sh -"
        node.vm.provision "shell", privileged: true, inline: "systemctl enable rke2-agent.service"
        node.vm.provision "shell", privileged: true, inline: "mkdir -p /etc/rancher/rke2"
        node.vm.provision "shell", privileged: true, inline: $write_rke2_config, args: [server['ip'], cluster['token'], "#{ip}"]
        node.vm.provision "shell", privileged: true, inline: "systemctl start rke2-agent.service"
      elsif bootstrap['name'] == 'k3s'
        node.vm.provision "shell", privileged: true, inline: <<-SHELL
          set -e -x -u
          export DEBIAN_FRONTEND=noninteractive

          export INSTALL_K3S_VERSION=#{bootstrap['version']}
          export K3S_URL=https://#{server['ip']}:6443
          export K3S_TOKEN=#{cluster['token']}
          export INSTALL_K3S_EXEC="--kubelet-arg \"v=#{kubelet['log-level']}\""

          curl -sfL https://get.k3s.io | sh -
        SHELL
      end
    end
  end
end
